### ISSUE TITLE
What have to changes made for android development for this feature

### ISSUE THREAD

**Issue by HKSOLDIER** [jeffreymendez1993/react-native-car-connect#4]
what are the changes and why it is not running the command "react-native run-android".

**Comment by j-mendez** [comment]
@HKSOLDIER Android needs to bridge https://developer.android.com/reference/android/media/AudioDeviceInfo with background support. Currently I am tight on time and only needed this for iOS so android was put on hold. You need to run `react-native run-android` in your own project after installing this module and linking the native modules. (android auto links, only iOS needs an extra command via `pod install`)

**Comment by HKSOLDIER** [comment]
Sir,
 I need in react native platform i need this because if i complete this
task i will get a job. My requirement is when a person enter's into his/her
car then it has to give a notification that "you are inside car" by using
bluetooth. Please sir give me some advice for completing this task.

**Comment by j-mendez** [comment]
@HKSOLDIER sure, I think it should look something like this

@Override
    public void onCreate() {
       AudioManager audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
        audioManager.requestAudioFocus(new AudioManager.OnAudioFocusChangeListener() {
            @Override
            public void onAudioFocusChange(int focusChange) {
               bluetoothIsConnected()
            }
        }, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN);
}


public final boolean bluetoothIsConnected() {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        PackageManager packageManager = getPackageManager();
        if (!packageManager.hasSystemFeature(PackageManager.FEATURE_AUDIO_OUTPUT)) {
            return false;
        }
        AudioManager audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
        AudioDeviceInfo[] devices = audioManager.getDevices(AudioManager.GET_DEVICES_OUTPUTS);
        for (AudioDeviceInfo device : devices) {
            if (device.getType() == AudioDeviceInfo.TYPE_BLUETOOTH_A2DP) {
                return true;
            }
        }
    }
    return false;
}

The ideal way should be something like this but, detecting the audio channels connectivity state. https://developer.android.com/guide/topics/media-apps/volume-and-earphones . You can also follow the iOS setup https://github.com/j-mendez/react-native-car-connect/blob/master/ios/CarConnect.swift for the android setup.

**Comment by HKSOLDIER** [comment]
Sir actually i need in "react native".

**Comment by j-mendez** [comment]
@HKSOLDIER the readme shows how you can use this package for react-native. Currently this package needs to bridge the native method over to react-native in order for this to work. This package only works for iOS currently. Hope this helps.

**Comment by j-mendez** [comment]
@HKSOLDIER 

`import { useEffect } from "react";
import CarConnect from "react-native-car-connect";
import { View, NativeEventEmitter } from "react-native";

const CarEvents = new NativeEventEmitter(CarConnect);

function App() {
  useEffect(
    () => {
      CarEvents.addListener("onConnect", res => {
        alert("Car connected state = ", res);
      });
      CarEvents.addListener("onDisconnect", res => {
        alert("Car disconnected state = ", res);
      });
      // pass in true to use background thread
      CarConnect.start(true);
      return () => {
        CarConnect.stop(true);
      };
    },
    [])

  // render your component/ui
  return <View />;
}`
