### ISSUE TITLE
Error on build 

### ISSUE THREAD

**Issue by pug-pelle-p** [jeffreymendez1993/react-native-car-connect#5]
Hi, I followed all the steps in the readme. But when I build my project I get 2 errors "2 duplicate symbols for architecture x86_64" and "linker command failed with exit code 1 (use -v to see invocation)"

I don't know how to solve this, any help on this would be greatly appreciated!

<img width="701" alt="Screenshot 2023-08-21 at 23 56 14" src="https://github.com/j-mendez/react-native-car-connect/assets/33658649/bbe48394-9fdf-4ba7-9b5d-9cafa42d3194">

**Comment by j-mendez** [comment]
@pug-pelle-p try cleaning the pods with `pod clean` and re-link. It could be an issue with the react-native version since this project used an older version for native exporting.

**Comment by pug-pelle-p** [comment]
I got it working by including the .xcworkspace instead of .xcodeproj
